# Generated by Django 4.1.1 on 2022-09-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Client Status')),
                ('discount', models.IntegerField(verbose_name='Discount')),
                ('visits_before_receiving', models.IntegerField(verbose_name='Number of visits before receiving')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Client name')),
                ('surname', models.CharField(max_length=255, verbose_name='Client surname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Client email')),
                ('visits', models.IntegerField(default=1, verbose_name='Number of client visits')),
                ('active', models.BooleanField(default=True, verbose_name='Preempts whether the client is active')),
                ('date_joining', models.DateField(auto_now_add=True, verbose_name='Date of joining')),
                ('date_visit', models.DateField(auto_now=True, verbose_name='Date of last visit')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clientstatus')),
            ],
        ),
    ]
