# Generated by Django 4.1.1 on 2022-09-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpromocode',
            name='active',
            field=models.BooleanField(default=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='clientpromocode',
            name='secret_number',
            field=models.CharField(default='ZXlTUC', max_length=6, verbose_name='Client promocode'),
        ),
    ]
