# Generated by Django 4.1.1 on 2022-09-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientpromocode_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpromocode',
            name='secret_number',
            field=models.CharField(default='w37x9z', max_length=6, verbose_name='Client promocode'),
        ),
    ]
