version: "3.8"
services:

  # Redis
  redis:
    image: redis:alpine
    container_name: redis

  # Database Postgres
  db:
    restart: always
    image: postgres:14.5
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_HOST_AUTH_METHOD: "trust"


  # Django Application
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  # Celery
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l DEBUG
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - db
      - redis
      - app